export const Icons = {
    home: require('../assest/Icons/home.png'),
    homeActive: require('../assest/Icons/home-active.png'),
    search: require('../assest/Icons/search.png'),
    searchActive: require('../assest/Icons/search-active.png'),
    box: require('../assest/Icons/box.png'),
    boxActive: require('../assest/Icons/box-active.png'),
    user: require('../assest/Icons/user.png'),
    userActive: require('../assest/Icons/user-active.png'),
    playButton: require('../assest/Icons/play-button.png'),
    pauseButton: require('../assest/Icons/pause.png'),
    bell:  require('../assest/Icons/bell.png'),
    bellAlert:  require('../assest/Icons/bell-alert.png'),
    list:  require('../assest/Icons/list.png'),
    gear: require('../assest/Icons/setting.png'),
    arrowDown: require('../assest/Icons/arrow-down.png'),

    next: require('../assest/Icons/next.png'),
    prev: require('../assest/Icons/previous.png'),
    fastForward: require('../assest/Icons/fast-forward.png'),
    fastBackward: require('../assest/Icons/fast-backward.png'),
    fullscreenExit: require('../assest/Icons/fullscreen-exit.png'),
    fullscreen: require('../assest/Icons/fullscreen.png'),
    threedots: require('../assest/Icons/dots.png'),
    arrowBack: require('../assest/Icons/arrowback.png'),
    arrowFront: require('../assest/Icons/arrowfront.png'),
    download: require('../assest/Icons/download.png'),
    insurance: require('../assest/Icons/insurance.png'),
    info: require('../assest/Icons/info.png'),
    support: require('../assest/Icons/support.png'),
    rating: require('../assest/Icons/rating.png'),
    envlope: require('../assest/Icons/mail.png'),
    logout: require('../assest/Icons/logout.png'),
    videosettings: require('../assest/Icons/videosetting.png'),
    videothumb: require('../assest/Icons/videothumb.png'),
    edit: require('../assest/Icons/pencil.png'),
    jump: require('../assest/Icons/jump.png'),
}